[32mINFO    [0m utils.driver_utils:driver_utils.py:23 WebDriver initialized successfully
[32mINFO    [0m pages.login_page:login_page.py:30 Navigated to: https://velvet.webredirect.himshang.com.np/#/pages/dashboard
[32mINFO    [0m pages.login_page:login_page.py:36 Entered username
[32mINFO    [0m pages.login_page:login_page.py:42 Entered password
[32mINFO    [0m pages.base_page:base_page.py:23 Clicked Sign In button using normal click
[32mINFO    [0m pages.login_page:login_page.py:56 Already Logged In popup detected
[32mINFO    [0m pages.base_page:base_page.py:23 Clicked Logout button using normal click
[32mINFO    [0m pages.login_page:login_page.py:60 Logout button clicked successfully
[32mINFO    [0m pages.login_page:login_page.py:67 Pressed Enter on Sign In button after logout
[32mINFO    [0m pages.base_page:base_page.py:23 Clicked Add Product button using normal click
[1m[31mERROR   [0m pages.product_master_page:product_master_page.py:290 Error saving product: Alert Text: Data Saved Successfully. Do you want to continue adding products to this group ?
Message: unexpected alert open: {Alert text : Data Saved Successfully. Do you want to continue adding products to this group ?}
  (Session info: chrome=138.0.7204.169)
Stacktrace:
	GetHandleVerifier [0x0x7ff73e5de935+77845]
	GetHandleVerifier [0x0x7ff73e5de990+77936]
	(No symbol) [0x0x7ff73e399cda]
	(No symbol) [0x0x7ff73e441582]
	(No symbol) [0x0x7ff73e4186a3]
	(No symbol) [0x0x7ff73e3e1791]
	(No symbol) [0x0x7ff73e3e2523]
	GetHandleVerifier [0x0x7ff73e8b684d+3059501]
	GetHandleVerifier [0x0x7ff73e8b0c0d+3035885]
	GetHandleVerifier [0x0x7ff73e8d0400+3164896]
	GetHandleVerifier [0x0x7ff73e5f8c3e+185118]
	GetHandleVerifier [0x0x7ff73e60054f+216111]
	GetHandleVerifier [0x0x7ff73e5e72e4+113092]
	GetHandleVerifier [0x0x7ff73e5e7499+113529]
	GetHandleVerifier [0x0x7ff73e5ce298+10616]
	BaseThreadInitThunk [0x0x7ff840aa7374+20]
	RtlUserThreadStart [0x0x7ff8419dcc91+33]
[32mINFO    [0m utils.driver_utils:driver_utils.py:33 Cleaning up - closing driver
[32mINFO    [0m utils.driver_utils:driver_utils.py:35 Driver closed successfully