{"uuid": "7f953878-49bd-4603-83fd-c69207c7e13c", "children": ["d7d0e5fe-3ac1-4d9b-880d-d73226d48b98"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "exceptions.custom_exceptions.WebDriverInitializationError: WebDriver initialization failed: Message: session not created: DevToolsActivePort file doesn't exist\nStacktrace:\n\tGetHandleVerifier [0x0x7ff6883be415+77285]\n\tGetHandleVerifier [0x0x7ff6883be470+77376]\n\t(No symbol) [0x0x7ff688189a6a]\n\t(No symbol) [0x0x7ff6881ccac9]\n\t(No symbol) [0x0x7ff6881c6b7c]\n\t(No symbol) [0x0x7ff6881c278e]\n\t(No symbol) [0x0x7ff68821602e]\n\t(No symbol) [0x0x7ff6882157c0]\n\t(No symbol) [0x0x7ff6882083e3]\n\t(No symbol) [0x0x7ff6881d1521]\n\t(No symbol) [0x0x7ff6881d22b3]\n\tGetHandleVerifier [0x0x7ff6886a1efd+3107021]\n\tGetHandleVerifier [0x0x7ff68869c29d+3083373]\n\tGetHandleVerifier [0x0x7ff6886bbedd+3213485]\n\tGetHandleVerifier [0x0x7ff6883d884e+184862]\n\tGetHandleVerifier [0x0x7ff6883e055f+216879]\n\tGetHandleVerifier [0x0x7ff6883c7084+113236]\n\tGetHandleVerifier [0x0x7ff6883c7239+113673]\n\tGetHandleVerifier [0x0x7ff6883ae298+11368]\n\tBaseThreadInitThunk [0x0x7ffe85327374+20]\n\tRtlUserThreadStart [0x0x7ffe8617cc91+33]\n\n", "trace": "  File \"C:\\Users\\karun\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\karun\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\karun\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\karun\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\karun\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\karun\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\karun\\PycharmProjects\\PythonProject\\project\\tests\\conftest.py\", line 24, in driver\n    return driver_manager.initialize_driver()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\karun\\PycharmProjects\\PythonProject\\New_flow\\utils\\driver_utils.py\", line 27, in initialize_driver\n    raise WebDriverInitializationError(f\"WebDriver initialization failed: {e}\")\n"}, "start": 1753850071477, "stop": 1753850354126}], "start": 1753850071477, "stop": 1753850382570}